# Generated by Django 5.2.4 on 2025-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodels',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='otpmodels',
            name='password_hash',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
