# Generated by Django 5.2.4 on 2025-07-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_otpmodels_name_otpmodels_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodels',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
