# Generated by Django 5.2.4 on 2025-08-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_otpmodels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingparticipant',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='booking.booking'),
        ),
    ]
