# Generated by Django 5.2.4 on 2025-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookingparticipant_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
