# Generated by Django 5.2.4 on 2025-08-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_description_booking_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_time'], name='booking_boo_room_id_5ca230_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'end_time'], name='booking_boo_room_id_aac680_idx'),
        ),
    ]
